Develop/gpt2
graphcore/portfolio-examples pull request #5
Opened 2021-11-25 12:04 UTC by ifromeast

This is the project to pre-train GPT2 on IPU.

2021-11-26 13:15 UTC, philb-graphcore requested changes
Looking good. A few minor things on the README & IP side I'd suggest we tidy up.

2021-11-26 13:15 UTC, philb-graphcore commented on pytorch/gpt2/README.md
> +SDK version: 2.4.0-EA.1+808_poptorch
We shouldn't be putting EA SDK numbers into the public domain.
If we are aligning this for the 2.4 release we should just say "SDK 2.4".

2021-11-26 13:15 UTC, philb-graphcore commented on pytorch/gpt2/README.md
> +The model has not converge to SOTA, and we are still working on this.
```suggestion
This model is under active development, and details on performance and convergence will be added soon. ```

2021-11-26 13:15 UTC, philb-graphcore commented on pytorch/gpt2/README.md
> +The newest results will be updated once we got it.
```suggestion
```

2021-11-26 13:15 UTC, philb-graphcore commented on pytorch/gpt2/run/pretraining.sh
> +#export POPLAR_ENGINE_OPTIONS='{"profiler.includeFlopEstimates": "true","autoReport.all":"true","debug.allowOutOfMemory": "true", "autoReport.executionProfileProgramRunCount":"1", "autoReport.directo
Do we want to leave the profiling enabled for this?

2022-03-17 08:54 UTC, internetoftim approved these changes
GPT2 M/L license review done

2022-03-17 08:56 UTC, internetoftim commented
GPT2 M/L update for SDK 2.5

2022-03-17 08:56 UTC, merged